/**
 * Astro route/collection/filename/frontmatter planner. Keeps URLs shallow (<=2
 * segments), uses content collections + generated routes (never per-page route
 * files), and avoids category sprawl. Produces titles/H1/format per page type.
 */
import type { PageType, PageRole, SearchIntent, FunnelStage } from '../core/types.ts';
import { slugify, titleCase, truncate } from '../core/text.ts';
import { corePhrase } from '../clustering/cluster.ts';
import { CONTENT_FORMAT } from '../config/defaults.ts';

export function collectionForType(pageType: PageType): string {
  switch (pageType) {
    case 'pillar':
    case 'category-hub':
    case 'sub-hub':
      return 'hubs';
    case 'comparison':
      return 'comparisons';
    case 'glossary':
      return 'glossary';
    case 'tool':
      return 'tools';
    case 'template':
    case 'checklist':
      return 'templates';
    default:
      return 'articles';
  }
}

export interface AstroPlan {
  slug: string;
  urlPath: string;
  astroRoute: string;
  astroCollection: string;
  markdownFilename: string;
  recommendedTitle: string;
  recommendedH1: string;
  recommendedContentFormat: string;
  tags: string[];
}

export function planAstro(opts: {
  primaryKeyword: string;
  pageType: PageType;
  role: PageRole;
  categorySlug: string;
  clusterSlug: string;
  subject: string;
}): AstroPlan {
  const { primaryKeyword, pageType, categorySlug, clusterSlug } = opts;
  const slug = slugify(primaryKeyword).slice(0, 70).replace(/-+$/, '');
  const collection = collectionForType(pageType);
  const ext = pageType === 'tool' ? 'mdx' : 'md';

  let urlPath: string;
  switch (pageType) {
    case 'pillar':
      urlPath = `/${slug}/`;
      break;
    case 'category-hub':
      urlPath = `/${categorySlug}/`;
      break;
    case 'sub-hub':
      urlPath = `/${categorySlug}/${clusterSlug}/`;
      break;
    case 'glossary':
      urlPath = `/glossary/${slug}/`;
      break;
    case 'comparison':
      urlPath = `/compare/${slug}/`;
      break;
    case 'tool':
      urlPath = `/tools/${slug}/`;
      break;
    case 'template':
    case 'checklist':
      urlPath = `/templates/${slug}/`;
      break;
    default:
      urlPath = `/${categorySlug}/${slug}/`;
  }

  return {
    slug,
    urlPath,
    astroRoute: urlPath, // generated by src/pages/[...slug].astro from the collection
    astroCollection: `src/content/${collection}/`,
    markdownFilename: `src/content/${collection}/${slug}.${ext}`,
    recommendedTitle: titleFor(pageType, primaryKeyword),
    recommendedH1: h1For(pageType, primaryKeyword),
    recommendedContentFormat: CONTENT_FORMAT[pageType],
    tags: tagsFor(opts.subject, categorySlug, pageType),
  };
}

function titleFor(pageType: PageType, kw: string): string {
  const T = titleCase(kw);
  const core = titleCase(corePhrase(kw) || kw);
  let t: string;
  switch (pageType) {
    case 'pillar':
      t = `${T}: The Complete Guide`;
      break;
    case 'category-hub':
      t = `${T}: Guides, Tools & Resources`;
      break;
    case 'sub-hub':
      t = `${T}: Everything You Need to Know`;
      break;
    case 'glossary':
      t = `What Is ${core}? Definition & Examples`;
      break;
    case 'comparison':
      t = `${T}: Which Should You Choose?`;
      break;
    case 'commercial':
      t = /^(best|top)/i.test(kw) ? `${T} (${new Date().getFullYear()})` : `${T}: Reviewed & Compared`;
      break;
    case 'faq':
      t = `${T}: Frequently Asked Questions`;
      break;
    case 'tool':
      t = `${T} (Free Tool)`;
      break;
    case 'template':
      t = `${T} (Free Download)`;
      break;
    case 'checklist':
      t = `${T} (Step-by-Step)`;
      break;
    case 'case-study':
      t = `${T}: A Real Example`;
      break;
    case 'longtail-question':
      t = /\?$/.test(kw) ? T : `${T}?`;
      break;
    default:
      t = T;
  }
  return truncate(t, 65);
}

function h1For(pageType: PageType, kw: string): string {
  const T = titleCase(kw);
  if (pageType === 'glossary') return `${titleCase(corePhrase(kw) || kw)}`;
  if (pageType === 'longtail-question') return /\?$/.test(kw) ? T : `${T}?`;
  return truncate(T, 70);
}

function tagsFor(subject: string, categorySlug: string, pageType: PageType): string[] {
  const tags = new Set<string>();
  tags.add(categorySlug);
  tags.add(pageType);
  for (const w of slugify(subject).split('-').slice(0, 2)) if (w) tags.add(w);
  return [...tags].slice(0, 5);
}
